name: FModel QA Builder

on:
  push:
    branches: [ dev ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
            project: FModel/FModel.csproj
            framework: net8.0-windows
            suffix: win-x64
            binary: FModel.exe
          - os: macos-latest
            rid: osx-x64
            project: FModel.Mac/FModel.Mac.csproj
            framework: net8.0
            suffix: macos-x64
            binary: FModel.Mac
          - os: macos-latest
            rid: osx-arm64
            project: FModel.Mac/FModel.Mac.csproj
            framework: net8.0
            suffix: macos-arm64
            binary: FModel.Mac
    runs-on: ${{ matrix.os }}
    
    env:
      CXXFLAGS: "-Wno-missing-template-arg-list-after-template-kw"

    steps:
      - name: GIT Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: .NET 8 Setup
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Download Native Dependencies (MacOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p FModel.Mac/Native/Mac
          curl -L https://github.com/WorkingRobot/OodleUE/raw/refs/heads/main/Engine/Source/Runtime/OodleDataCompression/Sdks/2.9.16/lib/Mac/liboo2coremac64.2.9.16.dylib -o FModel.Mac/Native/Mac/liboo2coremac64.dylib
          curl -L https://github.com/WorkingRobot/OodleUE/raw/refs/heads/main/Engine/Source/Runtime/OodleDataCompression/Sdks/2.9.16/lib/Mac/liboo2extmac64.2.9.16.dylib -o FModel.Mac/Native/Mac/liboo2extmac64.dylib

      - name: .NET Restore
        run: dotnet restore "${{ matrix.project }}" -r ${{ matrix.rid }}

      - name: .NET Publish
        run: dotnet publish "${{ matrix.project }}" -c Release --no-restore --no-self-contained -r ${{ matrix.rid }} -f ${{ matrix.framework }} -o "./Publish/" -p:PublishReadyToRun=false -p:PublishSingleFile=true -p:DebugType=None -p:GenerateDocumentationFile=false -p:DebugSymbols=false

      - name: ZIP File (Windows)
        if: matrix.os == 'windows-latest'
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: zip
          filename: ${{ github.sha }}-${{ matrix.suffix }}.zip
          path: ./Publish/${{ matrix.binary }}

      - name: ZIP File (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          zip -r ${{ github.sha }}-${{ matrix.suffix }}.zip Publish/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}-${{ matrix.suffix }}.zip
          path: ${{ github.sha }}-${{ matrix.suffix }}.zip
